theme: jekyll-theme-cayman
title: Hidden Markov Tree
description: A terrain-aware machine learning model that integrates data-driven hidden Markov model with physics-based topography constraints for observation-based flood inundation mapping.
